FROM nvidia/cuda:12.3.2-cudnn9-devel-ubuntu22.04
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get -y install tzdata
ENV TZ=Asia/Singapore
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

WORKDIR /app
COPY . .
ENV CUDA_VISIBLE_DEVICES=0
ENV CUDA_HOME=/usr/local/cuda \
     TORCH_CUDA_ARCH_LIST="6.0 6.1 7.0 7.5 8.0 8.6+PTX"

RUN apt-get update \
    && apt-get -y install python3\
    && apt-get -y install python3-pip\
    && apt-get -y install ffmpeg\
    && apt-get -y install libsm6\
    && apt-get -y install libxext6\
    && apt-get -y install build-essential && apt-get clean && apt-get autoremove && rm -rf /var/lib/apt/lists/*

ENV CUDA_HOME=/usr/local/cuda-12.3/
ENV PATH=/usr/local/cuda-12.3/bin:$PATH
ENV LD_LIBRARY_PATH=/usr/local/cuda-12.3/lib64:$LD_LIBRARY_PATH
USER root

RUN pip install --no-cache-dir --upgrade -r requirements.txt
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu121
RUN pip3 install pytorch-quantization==2.1.2 --extra-index-url https://pypi.ngc.nvidia.com
RUN pip3 install fastapi uvicorn Cython

RUN python3 -m pip install --no-cache-dir wheel
RUN python3 -m pip install --no-cache-dir --no-build-isolation -e .
# Expose the port that the API will run on
EXPOSE 8484
WORKDIR /app

CMD ["uvicorn", "api_dino:app", "--host", "0.0.0.0", "--port", "8484", "--reload"]